name: build

on:
    release:
        types: [published]

env:
  GOPRIVATE: "github.com/reemote/*"
  ECR_REGISTRY: 512374753291.dkr.ecr.eu-central-1.amazonaws.com
  ECR_REPO: data-products/data-platform/superset
  IMAGE_NAME: superset
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build:
    name: Create release
    runs-on: python:3.10
    steps:
      - name: gettime
        run: date
      - uses: actions/checkout@v3
      - name: Build
        run: |
            echo "Building release $IMAGE_TAG"
            sed "s/0.0.0/$IMAGE_TAG/" pyproject.toml
            poetry build
        




